name: Run Trend Collector

on:
  schedule:
    - cron: '0 */6 * * *' # Jalankan setiap 6 jam
  workflow_dispatch: # Memungkinkan eksekusi manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests # Tambahkan library lain jika perlu

      - name: Run collector script
        run: python scripts/collector.py

      # (Langkah untuk upload ke Supabase akan ditambahkan di sini)
 - name: Run collector script
        id: collector
        run: python scripts/collector.py

      - name: Trigger Vercel AI Function
        run: |
          curl -X POST \
          "${{ secrets.VERCEL_FUNCTION_URL }}" \
          -H "Content-Type: application/json" \
          -H "x-secret-key: ${{ secrets.INTERNAL_API_SECRET }}" \
          --data-binary "@trends_output.json"




